
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// 12/12/2008 10:11:22 AM
//----------------------------------------------------

using System;
namespace simple_calc {

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static readonly int REAL = 12;
  public static readonly int UMINUS = 8;
  public static readonly int MOD = 7;
  public static readonly int INTEGER = 11;
  public static readonly int DIVIDE = 6;
  public static readonly int error = 1;
  public static readonly int SEMI = 2;
  public static readonly int EOF = 0;
  public static readonly int LPAREN = 9;
  public static readonly int MINUS = 4;
  public static readonly int MACRO = 13;
  public static readonly int PLUS = 3;
  public static readonly int RPAREN = 10;
  public static readonly int TIMES = 5;
}
}

